# Устранение ошибок с HTTP 499 при работе облачной функции или контейнера {{ serverless-containers-name }}


## Описание проблемы {#issue-description}

В журнале работы облачной функции или контейнера {{ serverless-containers-name }} отображаются сообщения вида `Error: Code 499 Message: request cancelled`.

## Решение {#issue-resolution}

Ошибка вызвана таймаутом на стороне клиента, который вызывает функцию. Когда приложение отправляет запрос на выполнение функции, оно ожидает получить ответ в течение определённого времени. Часто этот лимит равен 60 секундам по умолчанию. Если функция не успевает завершить обработку и вернуть результат за это время, клиент разрывает соединение.

Попробуйте следующие решения:
- увеличить время ожидания ответа на стороне клиента, который вызывает функцию, если есть возможность его контролировать,
- разбить долгую задачу на несколько функций, запускаемых по таймеру — полезно, когда таймаут на стороне клиента изменить невозможно.

Если предыдущие варианты не помогли, добавьте логирование в код функции и проанализируйте логи. Мы подготовили пример настройки логирования работы облачных функций на Python в документации:
- [логирование выполнения функций на Python](../../../functions/lang/python/logging),
- [запись логов в журнал выполнения функции](../../../functions/operations/function/logs-write).

## Если проблема осталась {#if-issue-still-persists}

Если вышеописанные действия не помогли решить проблему, [создайте запрос в техническую поддержку]({{ link-console-support }}). При создании запроса укажите следующую информацию:

1. Идентификатор облачной функции или контейнера {{ serverless-containers-name }}.
1. Содержимое журнала работы облачной функции или контейнера. Журналы работы функции доступны в разделе **{{ ui-key.yacloud.serverless-functions.item.switch_logs }}** на странице функции в [Консоли управления]({{ link-console-main }}).
